name: Monitor GHCR Images
on:
  registry_package:
    types:
      - created

jobs:
  monitor_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get image name
        run: |
          image_name="${{ github.event.client_payload.container.tags[0] }}"
          echo "Image Name: $image_name"
