name: Sync File

on:
  registry_package:
    types: [published]

env:
  PR_NUMBER: ${{ github.event. }}

jobs:
  monitor_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get image name
        run: |
          image_name="${{ github.event_name }}"
          echo "Image Name: $image_name"
