name: Sync File

on:
  registry_package:
    types: [published]

jobs:
  monitor_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: ${{ github.event.registry_package.name }} uploaded to GHCR
        run: |
          image_name="${{ github.event.registry_package.name }}"
          tag_name = "${{ github.event.registry_package }}"
          echo "Image Name: $image_name"
